### PR TITLE
feat:initialize styles folder

### PR DESCRIPTION
**Pull request by LeVHoangduc**
@lenguyenthimy-agilityio @hungnguyenhuu-agilityio Please help me to check and merge

### CODE REVIEW

**Comment by hungnguyenhuu-agilityio** [comment]
@LeVHoangduc Why you are using utils folder instead of abstract folder in 7-1 pattern?

**Comment by LeVHoangduc** [comment]
@hungnguyenhuu-agilityio That's reference 7-1 pattern I follow https://gist.github.com/rveitch/84cea9650092119527bc

**Comment by hungnguyenhuu-agilityio** [comment]
Does it announce as official? I saw it just a suggestion and no one verify it right or wrong?

**Comment by LeVHoangduc** [comment]
@hungnguyenhuu-agilityio It's reference I received in my plan. Should i use abstract for instead?

**Comment by hungnguyenhuu-agilityio** [comment]
It depends on you choice, I just want to ask incase you know it clearly, if you don't get idea related, should follow the official. Do you think that?

**Comment by LeVHoangduc** [comment]
@hungnguyenhuu-agilityio yah i got it. It means, with utils folder, we use  certainly it. But with abstract folder, it contains some files we maybe don't use it. Summary, utils  is a smaller thing than abstract

**Comment by hungnguyenhuu-agilityio** [comment]
Thanks, that's what I need

**Pull request merged**
